-- Script de Migración Segura (SAFE MIGRATION)
-- Este script NO borra datos. Solo agrega columnas faltantes necesarias para la nueva versión.

-- 1. Tabla transactions: Asegurar columnas nuevas para control de estado y auditoría
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'completed';
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES auth.users(id);

-- 2. Asegurar índices para rendimiento (SAFE INDEX CREATION)
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(status);

-- 3. Tabla system_logs (si no existe, crearla; si existe, no tocar)
CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT NOT NULL, -- 'info', 'error', 'warn'
  message TEXT NOT NULL,
  component TEXT, -- 'auth', 'system', 'transaction'
  details JSONB,
  user_id UUID REFERENCES auth.users(id),
  action TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabla user_sessions (para manejo de sesiones seguras)
CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  refresh_token TEXT NOT NULL,
  access_token_jti TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  last_used_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Tabla backup_configurations (para el sistema de backups)
CREATE TABLE IF NOT EXISTS backup_configurations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  frequency TEXT NOT NULL, -- Cron expression
  retention_days INTEGER DEFAULT 30,
  is_active BOOLEAN DEFAULT TRUE,
  last_run_at TIMESTAMP WITH TIME ZONE,
  next_run_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Tabla backup_logs
CREATE TABLE IF NOT EXISTS backup_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id BIGINT REFERENCES backup_configurations(id),
  status TEXT NOT NULL, -- 'success', 'failed'
  file_path TEXT,
  file_size_bytes BIGINT,
  duration_ms INTEGER,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Fin del script
